// utils/png_generator.dart
// Provides PNG/screenshot export for the Ward Council program widget.
// Uses the screenshot package to capture a rendered widget as PNG bytes,
// then shares / saves via share_plus.

import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../models/ward_council_program.dart';

class PngGenerator {
  /// Capture the [child] widget as PNG bytes using [ScreenshotController].
  static Future<Uint8List?> captureWidget(
      ScreenshotController controller) async {
    try {
      return await controller.capture(pixelRatio: 2.0);
    } catch (e) {
      debugPrint('PNG capture error: $e');
      return null;
    }
  }

  /// Build the canonical Ward Council snapshot widget (no scroll, fixed size).
  static Widget buildSnapshot(WardCouncilProgram p) {
    return Material(
      color: Colors.white,
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            _header(p),
            const SizedBox(height: 12),
            _divider(),
            const SizedBox(height: 8),

            // Body rows
            if (p.presiding != null && p.presiding!.isNotEmpty)
              _row('Presiding', p.presiding!),
            if (p.openingPrayer != null && p.openingPrayer!.isNotEmpty)
              _row('Opening Prayer', p.openingPrayer!),
            if (p.closingPrayer != null && p.closingPrayer!.isNotEmpty)
              _row('Closing Prayer', p.closingPrayer!),

            if (p.agendaItems != null && p.agendaItems!.isNotEmpty) ...[
              const SizedBox(height: 8),
              _sectionTitle('Agenda'),
              for (final a in p.agendaItems!)
                _agendaRow(a.title, ''),
            ],

            if (p.handbookReading != null &&
                p.handbookReading!.isNotEmpty) ...[
              const SizedBox(height: 8),
              _row('Handbook Reading', p.handbookReading!),
            ],

            const SizedBox(height: 8),
            _divider(),
            const SizedBox(height: 4),
            Text(
              'Generated by Church Program Generator',
              style: TextStyle(
                  fontSize: 9, color: Colors.grey[500], fontStyle: FontStyle.italic),
            ),
          ],
        ),
      ),
    );
  }

  static Widget _header(WardCouncilProgram p) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          p.wardName ?? 'Ward Name',
          style: const TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Color(0xFF6A1B9A)),
        ),
        const Text(
          'Ward Council Meeting',
          style: TextStyle(fontSize: 14, color: Color(0xFF6A1B9A)),
        ),
        if (p.meetingDate != null)
          Text(
            _formatDate(p.meetingDate!.toIso8601String()),
            style: const TextStyle(fontSize: 12, color: Colors.grey),
          ),
      ],
    );
  }

  static Widget _divider() => Container(
      height: 1,
      color: const Color(0xFF6A1B9A).withValues(alpha: 0.3));

  static Widget _sectionTitle(String text) => Padding(
        padding: const EdgeInsets.only(bottom: 4, top: 4),
        child: Text(text,
            style: const TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.bold,
                color: Color(0xFF6A1B9A))),
      );

  static Widget _row(String label, String value) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 3),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
                width: 140,
                child: Text('$label:',
                    style: const TextStyle(
                        fontSize: 11, fontWeight: FontWeight.bold))),
            Expanded(
                child: Text(value, style: const TextStyle(fontSize: 11))),
          ],
        ),
      );

  static Widget _agendaRow(String presenter, String title) => Padding(
        padding: const EdgeInsets.only(left: 12, bottom: 2),
        child: Row(
          children: [
            const Text('• ', style: TextStyle(fontSize: 11)),
            Expanded(
              child: Text(
                presenter.isNotEmpty ? '$presenter: $title' : title,
                style: const TextStyle(fontSize: 11),
              ),
            ),
          ],
        ),
      );

  static String _formatDate(String dateStr) {
    try {
      final d = DateTime.parse(dateStr);
      const months = [
        '', 'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'
      ];
      return '${months[d.month]} ${d.day}, ${d.year}';
    } catch (_) {
      return dateStr;
    }
  }

  /// Save PNG bytes to a temp file and share via share_plus.
  static Future<void> shareAsPng(
      Uint8List bytes, String filename, BuildContext context) async {
    try {
      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(bytes);
      await Share.shareXFiles(
        [XFile(file.path, mimeType: 'image/png')],
        subject: filename.replaceAll('.png', ''),
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error exporting PNG: $e')),
        );
      }
    }
  }
}
